[package]
edition.workspace = true
name = "server"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.5"
tokio = {version = "1.0", features = ["full"]}
